### ISSUE TITLE
 SMTP DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by kahwooi** [andris9/nodemailer-smtp-transport#11]
I am using this SMTP settings:

```
secure: true,
ignoreTLS : true,
port: 465,
```

But I am getting this error, and not able to sent email:

```
[Error: DEPTH_ZERO_SELF_SIGNED_CERT]
```

**Comment by andris9** [comment]
`ignoreTLS` doesn't apply when connecting to port 465, so you can skip that. If you want to accept an invalid certificate, you can add additional `tls` config:

```
secure: true,
port: 465,
tls:  {
   rejectUnauthorized: false
}
```
