### ISSUE TITLE
Error: Invalid login

### ISSUE THREAD

**Issue by MetaCoderHirschl** [andris9/nodemailer-smtp-transport#12]
Greetings -- I see that this is a common issue and have looked through all the issues here and on nodemailer and don't see the answer for this simple problem....Can't connect to Gmail: error:
Error: Invalid login-- fails here:nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:387:15

--the credentials are correct and don't know where else to look. Have removed details that I read in other issues aren't necessary, e.g. service: 'Gmail' will cover host/port/secure. any help? Thanks for any clue you can offer. I'm working right now on the local side.
nodemailer: {
       // host: 'smtp.gmail.com',
       // port: 465,
       // secure: true,

        service: 'Gmail',
        auth: {
            user: 'a****@gmail.com',
            pass: '*****sdfasdf&dfsdfsdfa;me'
        },
        debug: true

**Comment by andris9** [comment]
Gmail tends to reject valid credentials if it thinks the login attempt is suspicious, for example when the login is initiated from a geographically different region than usual. You should either check that your account allows logins from "less secure apps" or if you use 2FA then create an application specific password for Nodemailer or use OAuth2 which is the most reliable login mechanism for Gmail. If you still have problems I'd suggest you to move to a dedicated provider like SendGrid or MailGun etc. that all offer reasonable free tier that is comparable to Gmail limits.
