### ISSUE TITLE
Fails to connect to a server that doesn't require authentication

### ISSUE THREAD

**Issue by davidraviv** [andris9/nodemailer-smtp-transport#14]
In case a server does not require authentication, the mailer tries to connect with user: username and password: password.
This is the options I'm sending:
```javascript
var transport = nodemailer.createTransport(smtpTransport({
  "host": "mail.mydomain.com",
  "port": 25,
  "auth": {},
  "debug": true
}));
```
This is the debug log:
>{ type: 'server', message: '220 vrnv02ax00378 ESMTP Postfix' }
>{ type: 'client',
  message: 'EHLO vrnv02ax00378.mydomain.com' }
>{ type: 'server',
  message: '250-vrnv02ax00378\n250-PIPELINING\n250-SIZE 10240000\n250-VRFY\n250-ETRN\n250-ENHANCEDSTATUSCODES\n250-8BITMIME\n250 DSN' }
>{ type: 'client',
  message: 'AUTH PLAIN AHVzZXJuYW1lAHBhc3N3b3Jk' }
>{ type: 'server',
  message: '503 5.5.1 Error: authentication not enabled' }
>{ type: 'socket', message: 'Closing connection to the server' }

The `AUTH PLAIN AHVzZXJuYW1lAHBhc3N3b3Jk` decodes to: usernamepassword. I also tried to remove the "auth" property from the option json, with the same results.
Auth property containing an empty user and pass (`{"user":"", "pass":""}`) didn't work as well.

**Comment by andris9** [comment]
Set auth value to false, not {}

**Comment by davidraviv** [comment]
I'm closing the issue.
The problem was on my side, the config object was merges with another object that contained the user and pass values.
