### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by steve-p-com** [andris9/nodemailer-smtp-transport#21]
I've been using nodemailer for a while to send email from an intranet server and it's been perfect, without any specific known issues. I was trivially creating a transport like this:

```
// create reusable transporter object using (default) SMTP transport
var transporter = nodemailer.createTransport({
    host: '172.31.250.143'
});
```

However, this broke last week. A post mortem revealed that TLS was enabled on the SMTP server. This results in the server sending 'STARTTLS', so I added the option to ignore TLS:

```
// create reusable transporter object using (default) SMTP transport
var transporter = nodemailer.createTransport({
    host: '172.31.250.143',
    ignoreTLS: true
});
```

However, this does not fix the crash which I am getting. The stack dump of the crash looks like this:

```
  "trace": [
    {
      "column": null,
      "file": null,
      "function": "Error",
      "line": null,
      "method": null,
      "native": true
    },
    {
      "column": 36,
      "file": "_tls_wrap.js",
      "function": "",
      "line": 929,
      "method": null,
      "native": false
    },
    {
      "column": 17,
      "file": "events.js",
      "function": "TLSSocket.emit",
      "line": 104,
      "method": "emit",
      "native": false
    },
    {
      "column": 8,
      "file": "_tls_wrap.js",
      "function": "TLSSocket._finishInit",
      "line": 460,
      "method": "_finishInit",
      "native": false
    }
  ],
  "stack": [
    "Error: unable to verify the first certificate",
    "    at Error (native)",
    "    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)",
    "    at TLSSocket.emit (events.js:104:17)",
    "    at TLSSocket._finishInit (_tls_wrap.js:460:8)"
  ],
  "level": "error",
  "message": "uncaughtException: unable to verify the first certificate"
```

It seems that there is some action occurring at a low level which setting ignoreTLS to true is not preventing. This is leaving me with a problem that seems insurmountable at the moment. Are there any workarounds I could try?

**Comment by AmberGunso** [comment]
Hi!

I use code like this:

var transporter = nodemailer.createTransport(smtpTransport({
    debug: false,
requireTLS: true,
host: 'test.com',
    port: 25,
secureConnection: false,
    auth: {
        user: 'login',
        pass: 'password'

},
tls: {
        ciphers:'SSLv3',

ca: [
fs.readFileSync('server`s certificate.txt')
],
rejectUnauthorized: false
}
}));

2015-08-25 13:23 GMT+03:00 Steve Powell <notifications@github.com>:

**Comment by steve-p-com** [comment]
I have got this working now, thanks. It turns out that setting options.ignoreTLS to true is all that is required. A different transporter object was being used than what I thought was the case, so the setting was not being applied. Now it is being applied, it's working fine.
