### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by DominicBoettger** [andris9/nodemailer-smtp-transport#27]
If i specificy a ipv6 address with options.host
like this
'[2a01:4444:222:111:2]'

nodemailer returns a getaddrinfo ENOTFOUND error. It seems that it's actually looking up the address instead of using it as ip address.

**Comment by andris9** [comment]
Bracket notation is for IPv6 URIs while Nodemailer expects a hostname or an IP address. Hostname value is passed unmodified to Node.js [net.connect](https://nodejs.org/api/net.html#net_net_connect_options_connectlistener) method which rejects it.

This is a working example for sending e-mail through Gmail IPv6 address:

```javascript
var transporter = nodemailer.createTransport({
    host: '2a00:1450:4010:c06::6d', // smtp.gmail.com IPv6
    port: 465,
    secure: true,
    tls: {
        rejectUnauthorized: false // IP address does not match hostname on cert
    },
    auth: {
        user: 'example@gmail.com',
        pass: '*****'
    }
});
```

**Comment by DominicBoettger** [comment]
Thank you! I will try that.
